FROM nginx:1.27.0

# Instalar dependencias necesarias
RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    ca-certificates \
    lsb-release \
    apt-transport-https

# Agregar repositorio de PHP
RUN curl -sSL https://packages.sury.org/php/README.txt | bash -x

# Instalar PHP y PHP-FPM
RUN apt-get update && apt-get install -y \
    php8.1-cli \
    php8.1-fpm \
    php8.1-xml \
    php8.1-mbstring \
    php8.1-zip \
    php8.1-curl \
    php8.1-gd \
    php8.1-dev \
    php8.1-xmlrpc \
    php8.1-imap \
    php8.1-opcache \
    php8.1-soap \
    php8.1-mysql \
    unzip -y

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copiar configuración de Nginx
# COPY ./docker/dev/nginx.conf /etc/nginx/nginx.conf
# COPY ./docker/dev/conf.d /etc/nginx/conf.d

# Configurar PHP-FPM para escuchar en todas las interfaces
# RUN sed -i 's/127.0.0.1:9000/0.0.0.0:9000/' /etc/php/8.0/fpm/pool.d/www.conf

WORKDIR /var/www/html

# Copiar el código fuente de la aplicación
COPY . /var/www/html

# Instalar dependencias de Composer
ENV COMPOSER_ALLOW_SUPERUSER 1
RUN composer install

# Dar permisos necesarios
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 storage bootstrap/cache

# Exponer el puerto 80
EXPOSE 80

# Comando para iniciar PHP-FPM y Nginx
CMD service php8.1-fpm start && nginx -g 'daemon off;'

