ARG NODE_VERSION=20.12.2
ARG PNPM_VERSION=8.11.0

#################################### LARAVEL BASE #####################################
FROM php:8.1.28-fpm

LABEL maintainer="Diego Carlos"

RUN apt-get update && apt-get install -y \
    zip \
    unzip \
    curl \
    locales \
    libzip-dev \
    libfreetype6-dev \
    jpegoptim optipng pngquant gifsicle \
    libjpeg62-turbo-dev \
    libpng-dev \
    nano \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd


# Instalar extensiones PHP
RUN docker-php-ext-install pdo_mysql exif gd opcache zip

# Instalar composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instalar Node.js
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

# Instalar PNPM
RUN npm install -g pnpm@${PNPM_VERSION}

ENV COMPOSER_ALLOW_SUPERUSER 1

WORKDIR /var/www/html
